theme: minima
title: Silent Siren
author: M Rushaid
email: mho.rushaid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings of an introverted guy. 

# social links
instagram_username: mho_rush
github_username:  MoRushaid

show_excerpts: true # set to false to remove excerpts on the homepage
